### ISSUE TITLE
Adding a new [admin] user

### ISSUE THREAD

**Issue by hffmnn** [bkonkle/rust-example-caster-api#95]
After running the installation steps successfully I have a running caster-api locally. Now there is one open question left:

How to add something like an admin user or a user at all? As far as I can see all of the queries and mutations need an existing user?

**Comment by bkonkle** [comment]
Hi! I set this up based on the kind of structure that most of the clients I've worked with use, where they have an external authentication and user management system that uses the OAuth2 protocol.

In my local testing, I typically use Auth0 because it's quick and easy to set up. In Production, my clients have also used Okta, AWS Cognito, Identity Server, or their own homegrown OAuth2 service.

For unit and integration testing, however, I'll typically mock the JWT validation process so that real tokens aren't needed.

For my Nakago framework, I'm eventually planning to provide all the pieces to quickly put together your own OAuth2 server for identity management, but I haven't had the time yet.

**Comment by hffmnn** [comment]
Hi and thanks for the quick response.

So that means I would have to:

- configure everything in `local.toml` beneath `[auth.client]`
- get me a valid token from e.g. Auth0 (this is something that can't be done via the api, right? It doesn't provide a login?).
- Set this in the auth header

Done?

So I don't have to configure this user in the database somehow?

Once again thanks a lot for this repo! 

EDIT: Or can you give some info what to put where (e.g. in the Auth0 case). I am feeling a little bit lost here.

**Comment by bkonkle** [comment]
Yes, that's correct. You don't need to do anything special in the database, because the `users/resolver.rs` file defines a `get_or_create_current_user()` method that is used to create the User based on their JWT token if this is the first time we've seen them. The `sub` value on the token becomes the `username` of the User.

To use Auth0 as my provider, I have a tenant created for "Caster API Dev" with my Applications => API screen set up like this:

![image](https://github.com/bkonkle/rust-example-caster-api/assets/30199/e1ce8f8c-403b-4212-aa86-f20e7ac25716)

I have my "Identifier" in the settings for `caster-api-local` set to "localhost", which is used as the `audience` parameter.

Then, I switch to the Applications => Applications screen on Auth0 and add a client application called "Caster (local)". I think the type of client application is a bit flexible - on one project I used "Machine to Machine", but on another application I used "Regular Web Application", and both seem to work fine. The important part is to take the Client ID and Client Secret from the application and add it to your `local.toml`, along with the url and audience configured earlier:

```toml
[auth]
url = "https://caster-api-dev.us.auth0.com"
audience = "localhost"

[auth.client]
id = "client_id" # Replace this with the actual value
secret = "client_secret" # Replace this with the actual value
```

Now comes the hard part - you need a client application to navigate an OAauth redirect flow to obtain a JWT that you can use with your API. This is out-of-scope for the API because each client application is different. In testing, however, I used a small utility that creates a token using a username/password flow instead: https://github.com/bkonkle/rust-example-caster-api/blob/main/apps/api/tests/test_utils.rs#L87

In order for this to work with Auth0, however, you need to make sure you enable "Password" as a Grant Type in your client application config:

![image](https://github.com/bkonkle/rust-example-caster-api/assets/30199/04aa6dfe-8787-41c3-8338-cd1852ba2361)

Authentication is a really complex topic, especially with all of the mitigations we have to do to prevent malicious actors from gaining an attack vector. 😅 I definitely want to work on a feature for Nakago that allows you to easily spin up your own OAuth2 server to navigate all this without having to configure an external provider, but I haven't had the time to implement it yet.

Good luck!

**Comment by hffmnn** [comment]
Hi and thanks for the extensive response 
👍🏻 Highly appreciated!!!

... and sorry for the late response. 

From my point this issue can be closed.
